
#include "Port_Setup.h"


// SYS.00005 Настройка портов входных разовых команд
void portSetupGpi(void)
{
	portsSetupAsInput(ADR_1_MCU_PORT, 					ADR_1_MCU_PIN);							// Сигнал с адресной перемычки ADR_1
	portsSetupAsInput(ADR_2_MCU_PORT, 					ADR_2_MCU_PIN);							// Сигнал с адресной перемычки ADR_2
	portsSetupAsInput(ADR_3_MCU_PORT, 					ADR_3_MCU_PIN);							// Сигнал с адресной перемычки ADR_3
	portsSetupAsInput(ADR_4_MCU_PORT, 					ADR_4_MCU_PIN);							// Сигнал с адресной перемычки ADR_4
	portsSetupAsInput(ADR_5_MCU_PORT, 					ADR_5_MCU_PIN);							// Сигнал с адресной перемычки ADR_5
	portsSetupAsInput(ADR_6_MCU_PORT, 					ADR_6_MCU_PIN);							// Сигнал с адресной перемычки ADR_6
	portsSetupAsInput(ADR_7_MCU_PORT, 					ADR_7_MCU_PIN);							// Сигнал с адресной перемычки ADR_7
	portsSetupAsInput(DI_MAIN_REZERV_MCU_PORT,	DI_MAIN_REZERV_MCU_PIN);		// Сигнал от узла DC/DC преобразователей (DI_Main_Rezerv)
	portsSetupAsInput(DI_AD7091R_BUSY_PORT,			DI_AD7091R_BUSY_PIN);		// 
}


// SYS.00006 Настройка портов выходных разовых команд
void portSetupGpo(void)
{
	portsSetupAsOutput(DO_CAN1_LED_GREEN_PORT,			DO_CAN1_LED_GREEN_PIN);
	portsSetupAsOutput(DO_CAN2_LED_GREEN_PORT,			DO_CAN2_LED_GREEN_PIN);
	portsSetupAsOutput(DO_MCU_STAT_LED_GREEN_PORT,	DO_MCU_STAT_LED_GREEN_PIN);
	portsSetupAsOutput(DO_MCU_ERROR_LED_RED_PORT,		DO_MCU_ERROR_LED_RED_PIN);
	portsSetupAsOutput(DO_MCP_RES_MCU_PORT,		DO_MCP_RES_MCU_PIN);	// Управление разрешением работы MCP
	PORT_SetBits(DO_MCP_RES_MCU_PORT,	DO_MCP_RES_MCU_PIN);
	portsSetupAsOutput(DO_AD7091R_CNV_PORT,	DO_AD7091R_CNV_PIN);		// 
	portsSetupAsOutput(DO_AD7091R_RST_PORT,	DO_AD7091R_RST_PIN);		// 
	PORT_SetBits(DO_AD7091R_RST_PORT,	DO_AD7091R_RST_PIN);
	portsSetupAsOutput(DO_MUX_ADR0_MCU_PORT,	DO_MUX_ADR0_MCU_PIN);		// 
	portsSetupAsOutput(DO_MUX_ADR1_MCU_PORT,	DO_MUX_ADR1_MCU_PIN);		// 
	portsSetupAsOutput(DO_MUX_EN_MCU_PORT,		DO_MUX_EN_MCU_PIN);		// 
}


// SYS.00008 Настройка CAN основной линии
void portSetupCanA(void)
{
	// CAN1_RX
	portSetupFunc(DO_CAN1_RX_MCU_PORT,	DO_CAN1_RX_MCU_PIN,	PORT_FUNC_OVERRID);
	portSetupOe(DO_CAN1_RX_MCU_PORT,		DO_CAN1_RX_MCU_PIN,	PORT_OE_IN);
	portSetupMode(DO_CAN1_RX_MCU_PORT,	DO_CAN1_RX_MCU_PIN,	PORT_MODE_DIGITAL);
	portSetupPdShm(DO_CAN1_RX_MCU_PORT,	DO_CAN1_RX_MCU_PIN,	PORT_PD_SHM_OFF);
	portSetupPd(DO_CAN1_RX_MCU_PORT,		DO_CAN1_RX_MCU_PIN,	PORT_PD_DRIVER);
	portSetupSpeed(DO_CAN1_RX_MCU_PORT,	DO_CAN1_RX_MCU_PIN,	PORT_SPEED_MAXFAST);
	
	// CAN1_TX
	portSetupFunc(DO_CAN1_TX_MCU_PORT,	DO_CAN1_TX_MCU_PIN,	PORT_FUNC_OVERRID);
	portSetupOe(DO_CAN1_TX_MCU_PORT,		DO_CAN1_TX_MCU_PIN,	PORT_OE_OUT);
	portSetupMode(DO_CAN1_TX_MCU_PORT,	DO_CAN1_TX_MCU_PIN,	PORT_MODE_DIGITAL);
	portSetupPdShm(DO_CAN1_TX_MCU_PORT,	DO_CAN1_TX_MCU_PIN,	PORT_PD_SHM_OFF);
	portSetupPd(DO_CAN1_TX_MCU_PORT,		DO_CAN1_TX_MCU_PIN,	PORT_PD_DRIVER);
	portSetupSpeed(DO_CAN1_TX_MCU_PORT,	DO_CAN1_TX_MCU_PIN,	PORT_SPEED_MAXFAST);
}


// SYS.00009 Настройка CAN резервной линии
void portSetupCanB(void)
{
	// CAN2_RX
	portSetupFunc(DO_CAN2_RX_MCU_PORT,	DO_CAN2_RX_MCU_PIN,	PORT_FUNC_ALTER);
	portSetupOe(DO_CAN2_RX_MCU_PORT,		DO_CAN2_RX_MCU_PIN,	PORT_OE_IN);
	portSetupMode(DO_CAN2_RX_MCU_PORT,	DO_CAN2_RX_MCU_PIN,	PORT_MODE_DIGITAL);
	portSetupPdShm(DO_CAN2_RX_MCU_PORT,	DO_CAN2_RX_MCU_PIN,	PORT_PD_SHM_OFF);
	portSetupPd(DO_CAN2_RX_MCU_PORT,		DO_CAN2_RX_MCU_PIN,	PORT_PD_DRIVER);
	portSetupSpeed(DO_CAN2_RX_MCU_PORT,	DO_CAN2_RX_MCU_PIN,	PORT_SPEED_MAXFAST);
	
	// CAN2_TX
	portSetupFunc(DO_CAN2_TX_MCU_PORT,	DO_CAN2_TX_MCU_PIN,	PORT_FUNC_ALTER);
	portSetupOe(DO_CAN2_TX_MCU_PORT,		DO_CAN2_TX_MCU_PIN,	PORT_OE_OUT);
	portSetupMode(DO_CAN2_TX_MCU_PORT,	DO_CAN2_TX_MCU_PIN,	PORT_MODE_DIGITAL);
	portSetupPdShm(DO_CAN2_TX_MCU_PORT,	DO_CAN2_TX_MCU_PIN,	PORT_PD_SHM_OFF);
	portSetupPd(DO_CAN2_TX_MCU_PORT,		DO_CAN2_TX_MCU_PIN,	PORT_PD_DRIVER);
	portSetupSpeed(DO_CAN2_TX_MCU_PORT,	DO_CAN2_TX_MCU_PIN,	PORT_SPEED_MAXFAST);
}


// SYS.00013 Настройка портов SPI1
void portSetupSpi1(void)
{
	// SSP1_RXD
	portSetupFunc(SPI1_MCP_MISO_MCU_PORT,		SPI1_MCP_MISO_MCU_PIN,	PORT_FUNC_ALTER);
	portSetupOe(SPI1_MCP_MISO_MCU_PORT,			SPI1_MCP_MISO_MCU_PIN,	PORT_OE_IN);
	portSetupMode(SPI1_MCP_MISO_MCU_PORT,		SPI1_MCP_MISO_MCU_PIN,	PORT_MODE_DIGITAL);
	portSetupPdShm(SPI1_MCP_MISO_MCU_PORT,	SPI1_MCP_MISO_MCU_PIN,	PORT_PD_SHM_OFF);
	portSetupPd(SPI1_MCP_MISO_MCU_PORT,			SPI1_MCP_MISO_MCU_PIN,	PORT_PD_DRIVER);
	portSetupSpeed(SPI1_MCP_MISO_MCU_PORT,	SPI1_MCP_MISO_MCU_PIN,	PORT_SPEED_MAXFAST);
		
	// SSP1_TXD
	portSetupFunc(SPI1_MCP_MOSI_MCU_PORT,		SPI1_MCP_MOSI_MCU_PIN,	PORT_FUNC_ALTER);
	portSetupOe(SPI1_MCP_MOSI_MCU_PORT,			SPI1_MCP_MOSI_MCU_PIN,	PORT_OE_OUT);
	portSetupMode(SPI1_MCP_MOSI_MCU_PORT,		SPI1_MCP_MOSI_MCU_PIN,	PORT_MODE_DIGITAL);
	portSetupPdShm(SPI1_MCP_MOSI_MCU_PORT,	SPI1_MCP_MOSI_MCU_PIN,	PORT_PD_SHM_OFF);
	portSetupPd(SPI1_MCP_MOSI_MCU_PORT,			SPI1_MCP_MOSI_MCU_PIN,	PORT_PD_DRIVER);
	portSetupSpeed(SPI1_MCP_MOSI_MCU_PORT,	SPI1_MCP_MOSI_MCU_PIN,	PORT_SPEED_MAXFAST);
	
	// SSP1_CLK
	portSetupFunc(SPI1_MCP_SCK_MCU_PORT,	SPI1_MCP_SCK_MCU_PIN,	PORT_FUNC_ALTER);
	portSetupOe(SPI1_MCP_SCK_MCU_PORT,		SPI1_MCP_SCK_MCU_PIN,	PORT_OE_OUT);
	portSetupMode(SPI1_MCP_SCK_MCU_PORT,	SPI1_MCP_SCK_MCU_PIN,	PORT_MODE_DIGITAL);
	portSetupPdShm(SPI1_MCP_SCK_MCU_PORT,	SPI1_MCP_SCK_MCU_PIN,	PORT_PD_SHM_OFF);
	portSetupPd(SPI1_MCP_SCK_MCU_PORT,		SPI1_MCP_SCK_MCU_PIN,	PORT_PD_DRIVER);
	portSetupSpeed(SPI1_MCP_SCK_MCU_PORT,	SPI1_MCP_SCK_MCU_PIN,	PORT_SPEED_MAXFAST);
	
	// SSP1_FSS
	portsSetupAsOutput(SPI1_MCP_CS_MCU_0_PORT,	SPI1_MCP_CS_MCU_0_PIN);
	PORT_SetBits(SPI1_MCP_CS_MCU_0_PORT,	SPI1_MCP_CS_MCU_0_PIN);	
	portsSetupAsOutput(SPI1_MCP_CS_MCU_1_PORT,	SPI1_MCP_CS_MCU_1_PIN);
	PORT_SetBits(SPI1_MCP_CS_MCU_1_PORT,	SPI1_MCP_CS_MCU_1_PIN);
	portsSetupAsOutput(SPI1_MCP_CS_MCU_2_PORT,	SPI1_MCP_CS_MCU_2_PIN);
	PORT_SetBits(SPI1_MCP_CS_MCU_2_PORT,	SPI1_MCP_CS_MCU_2_PIN);
	portsSetupAsOutput(SPI1_MCP_CS_MCU_3_PORT,	SPI1_MCP_CS_MCU_3_PIN);
	PORT_SetBits(SPI1_MCP_CS_MCU_3_PORT,	SPI1_MCP_CS_MCU_3_PIN);
}


// SYS.00013 Настройка портов SPI2
void portSetupSpi2(void)
{
	// SSP2_RXD
	portSetupFunc(SPI2_AD7091R_SDO_PORT,		SPI2_AD7091R_SDO_PIN,	PORT_FUNC_ALTER);
	portSetupOe(SPI2_AD7091R_SDO_PORT,			SPI2_AD7091R_SDO_PIN,	PORT_OE_IN);
	portSetupMode(SPI2_AD7091R_SDO_PORT,		SPI2_AD7091R_SDO_PIN,	PORT_MODE_DIGITAL);
	portSetupPdShm(SPI2_AD7091R_SDO_PORT,		SPI2_AD7091R_SDO_PIN,	PORT_PD_SHM_OFF);
	portSetupPd(SPI2_AD7091R_SDO_PORT,			SPI2_AD7091R_SDO_PIN,	PORT_PD_DRIVER);
	portSetupSpeed(SPI2_AD7091R_SDO_PORT,		SPI2_AD7091R_SDO_PIN,	PORT_SPEED_MAXFAST);
	
	// SSP2_TXD
	portSetupFunc(SPI2_AD7091R_SDI_PORT,		SPI2_AD7091R_SDI_PIN,	PORT_FUNC_ALTER);
	portSetupOe(SPI2_AD7091R_SDI_PORT,			SPI2_AD7091R_SDI_PIN,	PORT_OE_OUT);
	portSetupMode(SPI2_AD7091R_SDI_PORT,		SPI2_AD7091R_SDI_PIN,	PORT_MODE_DIGITAL);
	portSetupPdShm(SPI2_AD7091R_SDI_PORT,		SPI2_AD7091R_SDI_PIN,	PORT_PD_SHM_OFF);
	portSetupPd(SPI2_AD7091R_SDI_PORT,			SPI2_AD7091R_SDI_PIN,	PORT_PD_DRIVER);
	portSetupSpeed(SPI2_AD7091R_SDI_PORT,		SPI2_AD7091R_SDI_PIN,	PORT_SPEED_MAXFAST);
	
	// SSP2_CLK
	portsSetupAsOutput(SPI2_AD7091R_SCLK_PORT,	SPI2_AD7091R_SCLK_PIN);
	/*portSetupFunc(SPI2_AD7091R_SCLK_PORT,		SPI2_AD7091R_SCLK_PIN,	PORT_FUNC_ALTER);
	portSetupOe(SPI2_AD7091R_SCLK_PORT,			SPI2_AD7091R_SCLK_PIN,	PORT_OE_OUT);
	portSetupMode(SPI2_AD7091R_SCLK_PORT,		SPI2_AD7091R_SCLK_PIN,	PORT_MODE_DIGITAL);
	portSetupPdShm(SPI2_AD7091R_SCLK_PORT,	SPI2_AD7091R_SCLK_PIN,	PORT_PD_SHM_OFF);
	portSetupPd(SPI2_AD7091R_SCLK_PORT,			SPI2_AD7091R_SCLK_PIN,	PORT_PD_DRIVER);
	portSetupSpeed(SPI2_AD7091R_SCLK_PORT,	SPI2_AD7091R_SCLK_PIN,	PORT_SPEED_MAXFAST);*/
	
	// SSP2_FSS
	portsSetupAsOutput(SPI2_AD7091R_CS_PORT,	SPI2_AD7091R_CS_PIN);
	PORT_SetBits(SPI2_AD7091R_CS_PORT,	SPI2_AD7091R_CS_PIN);
}


// SYS.00004 Инициализация портов
void portsSetup(void)
{
	portSetupGpi();				// SYS.00005 Настройка портов входных разовых команд
	portSetupGpo();				// SYS.00006 Настройка портов выходных разовых команд
	portSetupCanA();			// SYS.00008 Настройка CAN основной линии
	portSetupCanB();			// SYS.00009 Настройка CAN резервной линии
												// SYS.00012 Настройка портов линии UART
	portSetupSpi1();			// SYS.00013 Настройка портов SPI
	portSetupSpi2();			// SYS.00013 Настройка портов SPI
}
